= POC : Spring FWK with Externalized Configuration
:toc:
:imagesdir: assets/images

== Description

Trying to do the same as in Spring Boot.

== Details

Spring’s `Environment` abstraction provides search operations over a configurable hierarchy of property sources.

The customization of property sources can be done through classes like `ConfigurableApplicationContext` and `MutablePropertySources`.

The entire mechanism is configurable.
Perhaps you have a custom source of properties that you want to integrate into this search.
To do so, implement and instantiate your own `PropertySource` and add it to the set of `PropertySources` for the current `Environment`.

See more in https://docs.spring.io/spring-framework/reference/core/beans/environment.html#beans-property-source-abstraction[`PropertySource` Abstraction].

== Activate a Spring Profile

To activate a profile named _dev_, there are multiple solutions, like:

=== JVM System Parameter

[source,bash]
----
-Dspring.profiles.active=dev
----

=== Environment Variable

[source,bash]
----
export SPRING_PROFILES_ACTIVE=dev
----

== References

* Spring Boot
** Externalized Configuration
*** https://docs.spring.io/spring-boot/reference/features/external-config.html
** Properties and Configuration
*** https://docs.spring.io/spring-boot/how-to/properties-and-configuration.html
* Spring
** PropertySource Abstraction
*** https://docs.spring.io/spring-framework/reference/core/beans/environment.html#beans-property-source-abstraction
** Using @PropertySource
*** https://docs.spring.io/spring-framework/reference/core/beans/environment.html#beans-using-propertysource
** Spring Profiles
*** https://www.baeldung.com/spring-profiles
* Quarkus
** Configuration reference guide
*** https://quarkus.io/guides/config-reference/
* MicroProfile Config
** https://microprofile.io/specifications/config/
* The Twelve-Factor App > Config
** https://12factor.net/config