= POC : Spring FWK with Externalized Configuration
:toc:
:imagesdir: assets/images

== Description

Trying to do the same as in Spring Boot.

== Goal

The goal is to be able to provide **multiple sources of config properties**,
in a defined order.
A given property will be searched in the different sources, until it is found, in the defined order.

The different sources should be at least, by order of priority :

- System properties
- Environment variables
- Application config file in `file:./config/application.properties`
- Application config file in `classpath:application.properties`

Other sources of config properties may be added.

== Details

Spring’s `Environment` abstraction provides search operations over a configurable hierarchy of property sources.

The customization of property sources can be done through classes like `ConfigurableApplicationContext` and `MutablePropertySources`.

The entire mechanism is configurable.
Perhaps you have a custom source of properties that you want to integrate into this search.
To do so, implement and instantiate your own `PropertySource` and add it to the set of `PropertySources` for the current `Environment`.

See more in https://docs.spring.io/spring-framework/reference/core/beans/environment.html#beans-property-source-abstraction[`PropertySource` Abstraction].

== Activate a Spring Profile

To activate a profile named _dev_, there are multiple solutions, like:

=== JVM System Parameter

[source,bash]
----
-Dspring.profiles.active=dev
----

=== Environment Variable

[source,bash]
----
export SPRING_PROFILES_ACTIVE=dev
----

== With Spring Web

If using Spring for a web application, this feature can also be used.

=== Java-based configuration, without web.xml

You must add initializers (`ProfilePropertySourceInitializer` required) in a subclass of :

- `AbstractContextLoaderInitializer` (spring-web), in method `getRootApplicationContextInitializers()`
- `AbstractAnnotationConfigDispatcherServletInitializer` (spring-webmvc), in method `getServletApplicationContextInitializers()`, if `DispatcherServlet` is needed

=== With web.xml

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<web-app>

    <listener>
        <listener-class>
            org.springframework.web.context.ContextLoaderListener
        </listener-class>
    </listener>

    <context-param>
        <param-name>contextConfigLocation</param-name>
        <param-value>
            org.example.config.RootConfig
        </param-value>
    </context-param>

    <context-param>
        <param-name>contextInitializerClasses</param-name>
        <param-value>
            org.example.context.ProfilePropertySourceInitializer
        </param-value>
    </context-param>

</web-app>
----

See also:

- https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-servlet/context-hierarchy.html[Spring Web MVC / DispatcherServlet / Context Hierarchy]
- https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-servlet/sequence.html[Spring Web MVC / DispatcherServlet / Processing]

== References

* Spring Boot
** Externalized Configuration
*** https://docs.spring.io/spring-boot/reference/features/external-config.html
** Properties and Configuration
*** https://docs.spring.io/spring-boot/how-to/properties-and-configuration.html
* Spring
** PropertySource Abstraction
*** https://docs.spring.io/spring-framework/reference/core/beans/environment.html#beans-property-source-abstraction
** Using @PropertySource
*** https://docs.spring.io/spring-framework/reference/core/beans/environment.html#beans-using-propertysource
** Spring Profiles
*** https://www.baeldung.com/spring-profiles
* Quarkus
** Configuration reference guide
*** https://quarkus.io/guides/config-reference/
* MicroProfile Config
** https://microprofile.io/specifications/config/
* The Twelve-Factor App > Config
** https://12factor.net/config